"""Add templates table

Revision ID: 93c82a2d1e1d
Revises: 111df21dc40c
Create Date: 2026-05-29 17:40:45.891008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93c82a2d1e1d'
down_revision: Union[str, Sequence[str], None] = '111df21dc40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_templates_category'), table_name='templates')
    op.drop_index(op.f('idx_templates_is_preset'), table_name='templates')
    op.drop_index(op.f('idx_templates_user_id'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('xml_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_preset', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preview_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('templates_pkey'))
    )
    op.create_index(op.f('idx_templates_user_id'), 'templates', ['user_id'], unique=False)
    op.create_index(op.f('idx_templates_is_preset'), 'templates', ['is_preset'], unique=False)
    op.create_index(op.f('idx_templates_category'), 'templates', ['category'], unique=False)
    # ### end Alembic commands ###
